# Applying the Buckingham $\pi$ theorem


*This notebook accompanies the ECE595 Data analytics course taught at Purdue in Fall 2022. These set of examples pertain to the materials of [Lecture 7.](https://github.com/alam740/Data-Analytics-Course/blob/master/Lecture-PDFs/ECE%20595%20-%20Lecture%2007.pdf)*

*Written by Jabir Bin Jahangir (jabir@purdue.edu)*



# Example 1:  Calculating the dimensionless variables

Let $L = f(T, k_B, h, R, E_B)$

The dimensions of the variables expressed in terms of basic dimensions
- $[T]  = M^0L^0t^0\theta^1$
- $[k_B]  = M^1L^2t^{-2}\theta^{-1}$
- $[h]  = M^1L^2t^{-2}\theta^{0}$
- $[R]  = M^0L^0t^{-1}\theta^{0}$
- $[E_B]  = M^1L^2t^{-2}\theta^{0}$

Determine a dimensionless $\pi$-group.

---


## Step by step solution

In [ ]:
from scipy.linalg import null_space
import numpy as np

# Number of variables 
N = 5; 

# Construct the dimensional matrix with exponents of the fundamental dimensions
D = np.array([[0, 0, 0, 1], [1, 2, -2, -1],[1, 2, -1, 0],[0, 0, -1, 0],[1, 2, -2, 0]])
print(D); 

[[ 0  0  0  1]
 [ 1  2 -2 -1]
 [ 1  2 -1  0]
 [ 0  0 -1  0]
 [ 1  2 -2  0]]


In [ ]:
# Determine the rank of the matrix
r = np.linalg.matrix_rank(D);
print(r);


3


In [ ]:
# number of pi parameters
pi_vars = N - r; 
print(pi_vars)

2


In [ ]:
# number of repeating variable
rep = r;  
print(r)

3


We seek solutions to  $\mathbf{D}\mathbf{E} = \begin{bmatrix}
\mathbf{P}&
\mathbf{Q} 
\end{bmatrix} \mathbf{E} = 0$  

Since, $\begin{bmatrix}
\mathbf{P} &
\mathbf{Q} 
\end{bmatrix}\begin{bmatrix}
\mathbf{-P^{-1}Q} & \mathbf{I} \end{bmatrix}^T = 0$ 

Therefore the exponent matrix, $\mathbf{E} = \begin{bmatrix}
\mathbf{-P^{-1}Q} & \mathbf{I} \end{bmatrix}^T$

In [ ]:
# First choose a non-singular submatrix
row_range = slice(0, 3)
col_range = slice(1, 4)

p_1  = D[row_range, col_range];
p_1 = np.linalg.inv(p_1); 
print(p_1)

[[-0.5 -0.5  1. ]
 [-1.  -1.   1. ]
 [ 1.   0.   0. ]]


In [ ]:
q_1 = -1 * D[3:6, 1:4];
print(q_1)

[[ 0  1  0]
 [-2  2  0]]


In [ ]:
# Calculating the exponent matrix
E_ = np.matmul(q_1, p_1);  # Intermediate result
E = np.hstack((E_, np.eye(pi_vars))) # Putting in all together
print(np.transpose(E));

[[-1. -1.]
 [-1. -1.]
 [ 1.  0.]
 [ 1.  0.]
 [ 0.  1.]]


$\pi_1 = \frac{hR}{k_BT}$ and $\pi_2 = \frac{E_B}{k_BT}$

## A faster way

Following code solves for the null space of the dimensional matrix

In [ ]:
from sympy import *;
init_printing(use_unicode=True)

D2 =  Matrix(np.transpose(D))
E2 = D2.nullspace()
E2

⎡⎡-1⎤  ⎡-1⎤⎤
⎢⎢  ⎥  ⎢  ⎥⎥
⎢⎢-1⎥  ⎢-1⎥⎥
⎢⎢  ⎥  ⎢  ⎥⎥
⎢⎢1 ⎥, ⎢0 ⎥⎥
⎢⎢  ⎥  ⎢  ⎥⎥
⎢⎢1 ⎥  ⎢0 ⎥⎥
⎢⎢  ⎥  ⎢  ⎥⎥
⎣⎣0 ⎦  ⎣1 ⎦⎦

# Generating all possible combinations

Applying Buckingham $\pi$-theorem it is possible to then generate all possible combination dimensionless $\pi$-groups. To do this, we will use the [BuckinghamPy package](https://github.com/saadgroup/BuckinghamPy). The package automatically carries out the above procedure to obtain other possible combinations. 

## Run the following cell to install the BuckinghamPy package.

In [ ]:

!git clone https://github.com/saadgroup/BuckinghamPy.git BuckinghamPy
!pip install ./BuckinghamPy/


Cloning into 'BuckinghamPy'...
remote: Enumerating objects: 473, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 473 (delta 51), reused 38 (delta 38), pack-reused 414
Receiving objects: 100% (473/473), 1.17 MiB | 3.77 MiB/s, done.
Resolving deltas: 100% (242/242), done.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing ./BuckinghamPy
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Created wheel for buckinghampy: filename=buckinghampy-1.0.2-py3-none-any.whl size=8319 sha256=c11962687cc37f8300e90d75885881737f2960792d052

In [ ]:
# from buckinghampy import BuckinghamPi

# example = BuckinghamPi()
# example.add_variable(name='T',dimensions='M^(0)*L^(0)*T^(0)*F')   
# example.add_variable(name='k',dimensions='M*L^(2)*T^(-2)*F^(-1)', non_repeating=True)                           
# example.add_variable(name='h',dimensions='M*L^(2)*T^(-1)*F^(0)')                      
# example.add_variable(name='R',dimensions='M^(0)*L^(0)*T^(-1)*F^(0)')           
# example.add_variable(name='E',dimensions='M*L^(2)*T^(-2)*F^(0)')                 


# example.generate_pi_terms()
# example.print_all()
# print('\n')
# print(example.variables)
# print(example.fundamental_variables)
# print(example._BuckinghamPi__null_spaces)
# print(example.M)
# print('\n')
# s = Matrix(example.M); 
# print(s.nullspace())

# Example 2: Newton anticipates Einstein's results

**Use Buckingham $\pi$ theorem to analyze the remarkable fact that Newton foresaw bending of light by gravity long
before Einstein!**

Assuming the sun can be treated as a point of mass m and the ray of light passes the mass with a distance of
closest approach $r$, dimensional reasoning helps to predict the defection angle $\theta$. The problem involves 3
of the 7 fundamental units: mass M, length L, and time T

Consider we first guess $\theta$ depends on only $r$ and $m$. The dimensions of this variables are $[\theta] = 1$, $[r] = M^0L^1T^0$, $[m] = M^1L^0T^0$. 

In [ ]:
from buckinghampy import BuckinghamPi

ex2 = BuckinghamPi()
ex2.add_variable(name='{\\theta}',dimensions='1') 
ex2.add_variable(name='r',dimensions='M^(0)*L^(1)*T^(0)') 
ex2.add_variable(name='m',dimensions='M^(1)*L^(0)*T^(0)') 



In [ ]:
try:
  ex2.generate_pi_terms()
except Exception as e:
  print(e)

The number of variables has to be greater than the number of physical dimensions.


We find that there are no solutions to the dimensional matrix. Thus we cannot write a dimensionally homogenous equation for $\theta$ with these variables alone and must consider additional dimensional constants or variables. It turns out to get a physical solution we need to introduce gravitational constant $G$ and light velocity  $c$ to the mix. 

In [ ]:
ex2.add_variable(name='G',dimensions='M^(-1)*L^(3)*T^(-2)')
ex2.add_variable(name='c',dimensions='M^(0)*L^(1)*T^(-1)')

ex2.generate_pi_terms()
ex2.print_all()

<IPython.core.display.Math object>

---

<IPython.core.display.Math object>

---

Therefore, we may write $\theta = f(\frac{Gm}{c^2r})$. Different theories predict $\theta \propto \frac{Gm}{c^2r}$ or $\theta = \alpha \frac{Gm}{c^2r}$ where $\alpha$ is a dimensionless constant. While Einstein's general relativity asserts $\alpha$ = 4, the simpler newtonian mechanics predicts $\alpha$ = 2.

### The GUI application

Following cell contains a convenient graphical UI implementation to perform the above routines. 

To redo the example above using this GUI, set "Number of Variables: $5$, then in the first row write, "Name: $\theta$ and "Dimensions: 1"; in the second row: "Name: $m$ and Dimensions=M; Third row, "Name: $\rm r$" and "Dimensions: $\rm L$", Fourth row: "Name: $G$" and Dimensions: $ \rm L^3/M/T/T$; Fifth row, "Name: $\rm c$" and "Dimensions: ${\rm L/T}$. Then press the small "Generate" button to get the scaled variables. It will produce the following results: $\displaystyle \quad\pi_1 = \frac{c^{2} r}{G m} \quad {\rm and}  \quad\pi_2 = \theta \quad$,as expected. 


In [ ]:
from buckinghampy import BuckinghamPiGui

GUI=BuckinghamPiGui()

Output()